### ISSUE TITLE
既然用spring boot了，能不能零配置文件加载dubbo？

### ISSUE THREAD

**Issue by Dreampie** [Percy0601/boot-dubbo#2]

**Comment by Percy0601** [comment]
可以的 遵循spring boot写个starter就可以了

**Comment by Dreampie** [comment]
求指导，刚刚接触spring boot，不知道怎么入手

**Comment by Percy0601** [comment]
看官方文档

**Comment by Dreampie** [comment]
我看了，但是没看到怎么实现一个您说的starter

**Comment by Percy0601** [comment]
如果好实现我就这么做了  官方每个组件 插件都是一个starter

**Comment by Percy0601** [comment]
@Dreampie 我没认真研究这个  如果你写了  记得分享后告诉我  应该不太难  Spring Boot的架构还是不错的  你可以认真学习研究下

**Comment by kimmking** [comment]
其实，，我以为你这个是个starter，，，原来不是。

**Comment by Percy0601** [comment]
@kimmking 不是，我看很多人有写starter

**Comment by Percy0601** [comment]
@Dreampie 其实我做这个脚手架最主要就是减少dubbo的依赖，其实对于dubbo/dubbox本来说还可以再瘦身升级，首先服务端和客户端依赖包就不一样，一个是外部依赖，另一个就是dubbo本身模块依赖。其实大家看到的dubbo就是dubbo-all这个模块，可以把这个再瘦身，做出一个极简版-推荐使用的dubbo来。。。
