### ISSUE TITLE
使用的流程能不能再具体点啊，怎么运行起来？

### ISSUE THREAD

**Issue by youngqiankun** [Percy0601/boot-dubbo#6]

**Comment by Percy0601** [comment]
@kingyoungfan 先把dubbox安装到本地  mvn clean install -Dmaven.test.skip=true
然后把我这个示例导入到IDE中  可以是Eclipse 或者 IDEA中 然后运行zookeeper,如果不使用注册中心zookeeper则需要修改配置文件,具体参考dubbo.io这个网址的用户文档 使用愉快 有时间我想重构dubbo dubbo的架构很好,很赞 学习dubbo让你水平提升很多
