### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by muniao** [Percy0601/boot-dubbo#8]
mvn clean install -Dmaven.test.skip=true

编译 boot-dubbo-infrastructure项目时发生错误：
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage (default) on project boot-dubbo-infrastructure: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.2.3.RELEASE:repackage failed: Unable to find main class

**Comment by Percy0601** [comment]
你导入到IDEA/Eclipse中   这个问题需要调整Maven的pom.xml  本来就是为了演示的使用的

**Comment by Percy0601** [comment]
@muniao 其实这个问题好解决  maven提示的很清楚的  自己应该可以解决的
